### PR TITLE
Change default port for NEST Server

### PR DESCRIPTION
**Pull request by babsey**
According to the discussion in the issue [#2321](https://github.com/nest/nest-simulator/issues/2321), the port 5000 seems having conflicts with other services. 
Thus we decided that the default port for NEST Server is now 52425.

Please review this PR after the merged PR [#2505](https://github.com/nest/nest-simulator/pull/2505) in NEST Simulator.

### CODE REVIEW

**Review by steffengraber — COMMENTED** [review]
Only the ports for the current dev image are changed. The changed description does not reflect this. Or should the port also be changed for the older images?

**Comment by babsey** [comment]
I do not think so. The older NEST Server runs on port 5000 by default.
We can tell people that NEST Server change its port in release v3.4.

@jougs @heplesser What do you think about Steffens suggestion?

**Review by jougs — APPROVED** [review]
I agree. This should only change in newer versions. The title of the PR against the NEST Simulator repository will automatically be ending up in the release notes of the next NEST release.

**Review by steffengraber — APPROVED** [review]
:+1:

**Pull request merged**
