### PR TITLE
Added pathlib patch for 3.3

### PR DESCRIPTION
**Pull request by steffengraber**

### CODE REVIEW

**Comment by terhorstd** [comment]
Hey! Good catch! Could you also feed this back to nest upstream? – Thanks!

**Comment by steffengraber** [comment]
Already done - https://github.com/nest/nest-simulator/pull/2353. I still have to integrate the end result here

**Comment by heplesser** [comment]
@steffengraber In https://github.com/nest/nest-simulator/pull/2353, we removed `pathlib` entirely, since it is part of the Python standard library. This PR replaces it by `pathlib2` in the requirements. Is that necessary, or can we drop `pathlib2` here as well, as in NEST itself?

**Comment by steffengraber** [comment]
@heplesser I will also remove it here.

**Pull request merged**
